# 配置数据源
spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/wdh?useSSL=false&serverTimezone=CST&allowPublicKeyRetrieval=true
      username: wdh
      password: 123456789
   redis:
      host: 127.0.0.1
      port: 6379
      database: 8
server.port: 8010
